XmlValidator/Controllers/ValidatorController.cs
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Serialization;
using XmlValidation;
using XmlValidator.Extensions;
using XmlValidator.Models;
using static System.Net.Mime.MediaTypeNames;

namespace XmlValidator.Controllers
{
    public class ValidatorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Validate(string PathToXml)
        {
            PathToXml = @"C:\Users\Admin\Desktop\testXml\1.xml";
            //@"C:\Users\Admin\Desktop\testXml\2.xml",
            //@"C:\Users\Admin\Desktop\testXml\3.xml",
            //@"C:\Users\Admin\Desktop\testXml\C11092867090_20240621T133433Z_JPCS-8.xml",
            //@"C:\Users\Admin\Desktop\testXml\1.1-Invoice-Sample.xml",
            //@"C:\Users\Admin\Desktop\testXml\1.1-Invoice-MultiLineItem-Sample.xml",
            var xmlFiles = GetXmlFiles(PathToXml);
            List<Rootobject> BaseXmls = new List<Rootobject>();
            List<ErrorModel> ValidationErrors = new List<ErrorModel>();
            string jsonText = string.Empty;
            foreach (var xmlFile in xmlFiles)
            {
                try
                {
                    string sourceFilePath = xmlFile;
                    string fileName = Path.GetFileName(sourceFilePath);
                    string destinationPath = Path.Combine(Server.MapPath("~/FilesForJson"), fileName);
                    System.IO.File.Copy(sourceFilePath, destinationPath, true);
                    XmlDocument xmlDoc = new XmlDocument();

                    using (Stream stream = new FileStream(destinationPath, FileMode.Open))
                    {
                        xmlDoc.Load(stream);
                    }
                    jsonText = JsonConvert.SerializeXmlNode(xmlDoc);
                    jsonText = new ValidationExtension().JsonHandler(jsonText);
                    Rootobject invoice = JsonConvert.DeserializeObject<Rootobject>(jsonText);
                    BaseXmls.Add(invoice);
                }
                catch (Exception ex)
                {
                    ErrorModel ErrorObj = new ErrorModel();
                    ErrorObj.errMsg = "XML format error " + ex.Message;
                    ValidationErrors.Add(ErrorObj);
                    return Json(new { errors = ValidationErrors });
                }
            }
            if (BaseXmls.Count > 0 && BaseXmls != null)
            {
                foreach (var item in BaseXmls)
                {
                    Invoice Invoice = item.Invoice;
                    string errorMsg = string.Empty;
                    if (Invoice != null)
                    {
                        #region Headervalidation/
                        List<ErrorModel> _Headervalidation = new List<ErrorModel>();
                        _Headervalidation = new ValidationExtension().ValidatePropertySize(Invoice.ID, nameof(Invoice) + "Id", 26);
                        if (!string.IsNullOrWhiteSpace(Invoice.ID))
                        {
                            _Headervalidation.Add(new ValidationExtension().ValidatePropertyNormalization(Invoice.ID, nameof(Invoice) + "Id"));
                        }
                        if (_Headervalidation.Count > 0)
                        {
                            foreach (var error in _Headervalidation)
                            {
                                if (!string.IsNullOrWhiteSpace(error.errMsg))
                                    ValidationErrors.Add(error);
                            }
                        }
                        _Headervalidation = new ValidationExtension().ValidatePropertySize(Invoice.IssueDate, nameof(Invoice.IssueDate), 10);
                        if (!string.IsNullOrWhiteSpace(Invoice.IssueDate))
                        {
                            _Headervalidation.Add(new ValidationExtension().ValidateDateProperty(Invoice.IssueDate, nameof(Invoice.IssueDate)));
                        }
                        if (_Headervalidation.Count > 0)
                        {
                            foreach (var error in _Headervalidation)
                            {
                                if (!string.IsNullOrWhiteSpace(error.errMsg))
                                    ValidationErrors.Add(error);
                            }
                        }
                        _Headervalidation = new ValidationExtension().ValidatePropertySize(Invoice.IssueTime, nameof(Invoice.IssueTime), 9);
                        if (!string.IsNullOrWhiteSpace(Invoice.IssueTime))
                        {
                            _Headervalidation.Add(new ValidationExtension().ValidateTimeProperty(Invoice.IssueTime, nameof(Invoice.IssueTime)));
                        }
                        if (_Headervalidation.Count > 0)
                        {
                            foreach (var error in _Headervalidation)
                            {
                                if (!string.IsNullOrWhiteSpace(error.errMsg))
                                    ValidationErrors.Add(error);
                            }
                        }
                        if (Invoice.InvoiceTypeCode != null)
                        {
                            _Headervalidation = new ValidationExtension().ValidatePropertySize(Invoice.InvoiceTypeCode.listVersionID, nameof(Invoice.InvoiceTypeCode.listVersionID), 5);
                            if (!string.IsNullOrWhiteSpace(Invoice.InvoiceTypeCode.listVersionID))
                            {
                                _Headervalidation.Add(new ValidationExtension().ValidatePropertyNormalization(Invoice.InvoiceTypeCode.listVersionID, nameof(Invoice.InvoiceTypeCode.listVersionID)));
                            }
                            if (_Headervalidation.Count > 0)
                            {
                                foreach (var error in _Headervalidation)
                                {
                                    if (!string.IsNullOrWhiteSpace(error.errMsg))
                                        ValidationErrors.Add(error);
                                }
                            }
                            _Headervalidation = new ValidationExtension().ValidatePropertySize(Invoice.InvoiceTypeCode.text, nameof(Invoice.InvoiceTypeCode), 2);
                            if (!string.IsNullOrWhiteSpace(Invoice.InvoiceTypeCode.text))
                            {
                                _Headervalidation.Add(new ValidationExtension().ValidateInvoiceType(Invoice.InvoiceTypeCode.text, nameof(Invoice.InvoiceTypeCode)));
                                _Headervalidation.Add(new ValidationExtension().ValidatePropertyNormalization(Invoice.InvoiceTypeCode.text, nameof(Invoice.InvoiceTypeCode)));
                            }
                            if (_Headervalidation.Count > 0)
                            {
                                foreach (var error in _Headervalidation)
                                {
                                    if (!string.IsNullOrWhiteSpace(error.errMsg))
                                        ValidationErrors.Add(error);
                                }
                            }
                        }
                        else
                        {
                            ValidationErrors.Add(new ErrorModel
                            {
                                errMsg = "InvoiceTypeCode is mandatory.",
                                PropertyName = "InvoiceTypeCode",
                                PropertyValue = null
                            });
                        }
                        _Headervalidation = new ValidationExtension().ValidatePropertySize(Invoice.DocumentCurrencyCode, nameof(Invoice.DocumentCurrencyCode), 3);
                        if (!string.IsNullOrWhiteSpace(Invoice.DocumentCurrencyCode))
                        {
                            _Headervalidation.Add(new ValidationExtension().ValidatePropertyNormalization(Invoice.DocumentCurrencyCode, nameof(Invoice.DocumentCurrencyCode)));
                            _Headervalidation.Add(new ValidationExtension().ValidateCurrencyType(Invoice.DocumentCurrencyCode, nameof(Invoice.DocumentCurrencyCode)));
                        }
                        if (_Headervalidation.Count > 0)
                        {
                            foreach (var error in _Headervalidation)
                            {
                                if (!string.IsNullOrWhiteSpace(error.errMsg))
                                    ValidationErrors.Add(error);
                            }
                        }
                        if (!string.IsNullOrWhiteSpace(Invoice.TaxCurrencyCode))
                        {
                            _Headervalidation = new ValidationExtension().ValidatePropertySize(Invoice.TaxCurrencyCode, nameof(Invoice.TaxCurrencyCode), 3);
                            _Headervalidation.Add(new ValidationExtension().ValidatePropertyNormalization(Invoice.TaxCurrencyCode, nameof(Invoice.TaxCurrencyCode)));
                            _Headervalidation.Add(new ValidationExtension().ValidateCurrencyType(Invoice.TaxCurrencyCode, nameof(Invoice.TaxCurrencyCode)));
                            if (_Headervalidation.Count > 0)
                            {
                                foreach (var error in _Headervalidation)
                                {
                                    if (!string.IsNullOrWhiteSpace(error.errMsg))
                                        ValidationErrors.Add(error);

XmlValidator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar {
            padding: 1rem 2rem;
        }

        .navbar-brand {
            font-size: 1.5rem;
            font-weight: bold;
        }

        .nav-link {
            padding: 0.5rem 1rem;
        }

        .navbar-dark .navbar-nav .nav-link:hover {
            color: #f8f9fa;
        }
        .navbar {
            padding: 1rem 2rem;
            background-color: #343a40; 
        }

        .navbar-brand {
            font-size: 1.5rem;
            font-weight: bold;
            color: #ff79c6;
        }

        .nav-link {
            padding: 0.5rem 1rem;
            color: #f8f8f2;
        }

        .navbar-dark .navbar-nav .nav-link:hover {
            color: #f8f9fa; 
        }

        .container.body-content {
            color: #f8f8f2; 
        }

        footer {
            color: #6272a4; 
        }
        .navbar {
            padding: 1rem 2rem;
            background-color: #343a40; 
        }

        .navbar-brand {
            font-size: 1.5rem;
            font-weight: bold;
            color: #ff79c6; 
        }

        .nav-link {
            padding: 0.5rem 1rem;
            color: #f8f8f2;
        }

        .navbar-dark .navbar-nav .nav-link:hover {
            color: #f8f9fa;
        }

        .container.body-content {
            min-height: calc(100vh - 162px);
            display: flex;
            flex-direction: column;
        }

        footer {
            margin-top: auto;
            color: #6272a4; 
            text-align: center;
            padding: 1rem 0;
            background-color: #282a36; 
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark">
        <div class="container">
            @Html.ActionLink("Xml Validator", "Index", "Validator", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <footer>
        <div class="container">
            <p>&copy; @DateTime.Now.Year - Pk's App</p>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>